### PR TITLE
Alexanda profile page

### PR DESCRIPTION
**Pull request by Alexandafransi**
## Profile Page

profilePage

### CODE REVIEW

**Review by mtuchi — CHANGES_REQUESTED** [review]
Remove this file `html-css/alex.html`
For this assignment for the user profile all files should be inside `user-profile` folder

**Comment by Alexandafransi** [comment]
Hey I have finish the changes @mtuchi

**Comment by Alexandafransi** [comment]
# image changes

change on the image

**Comment by Alexandafransi** [comment]
### Alex Movies Page @mtuchi 

moviePage

**Comment by mtuchi** [comment]
> Alex Movies Page
> moviePage
@Alexandafransi 
Make a different PR for this task

**Pull request closed without merging**
